### PR TITLE
I18 latest

### PR DESCRIPTION
**Pull request by TianMengLucky**

### CODE REVIEW

**Comment by TianMengLucky** [comment]
Currently having problems finding a way to reload components within +layout.svelte

**Comment by TianMengLucky** [comment]
Others can be implemented using goto(‘/’, { invalidateAll: true })

**Comment by TianMengLucky** [comment]
Consider adding automatic reboot for language switching

**Comment by TianMengLucky** [comment]
> Consider adding automatic reboot for language switching

@Kesomannen

**Comment by TianMengLucky** [comment]
image

**Comment by TianMengLucky** [comment]
image
If there's nothing wrong with it consider merging it, as the basic functionality has already been implemented

**Comment by TianMengLucky** [comment]
@Kesomannen Can you review and merge it?

**Comment by Kesomannen** [comment]
I'll get to this in a bit, sorry for taking so long.

**Comment by TianMengLucky** [comment]
Conflict resolution completed

**Comment by TianMengLucky** [comment]
> I'll get to this in a bit, sorry for taking so long.

Can you tell me why?

**Comment by xllifi** [comment]
Why was this closed? What happened?

**Pull request closed without merging**
